import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "ENBUILT | Spatial & Structural Design",
    template: "%s | ENBUILT",
  },
  description: "Architectural landmarks built for permanence. Monolithic form meeting technical precision.",
  metadataBase: new URL("https://enbuiltdesign.com"),
  openGraph: {
    title: "ENBUILT | Spatial & Structural Design",
    description: "Architectural landmarks built for permanence.",
    url: "https://enbuiltdesign.com",
    siteName: "ENBUILT",
    // OG/Twitter images are generated by src/app/opengraph-image.tsx via the
    // Next.js file convention — no images array needed here.
    locale: "en_US",
    type: "website",
  },
};
