import { Project, ProjectCategory } from "./types";

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "The Meridian",
    subtitle: "High-density mixed-use tower",
    category: "Commercial",
    location: "Chennai, IN",
    coords: "13.0827° N, 80.2707° E",
    year: "2024",
    area: "4,200 m²",
    status: "Completed",
    index: "01",
    size: "tall",
    imageSrc: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&q=80&auto=format",
    imageAlt: "The Meridian Tower",
    href: "/projects/meridian-tower",
  },
  {
    id: 2,
    title: "Casa Volta",
    subtitle: "Sculptural private residence",
    category: "Residential",
    location: "Coimbatore, IN",
    coords: "11.0168° N, 76.9558° E",
    year: "2023",
    area: "680 m²",
    status: "Completed",
    index: "02",
    size: "square",
    imageSrc: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80&auto=format",
    imageAlt: "Casa Volta Residence",
    href: "/projects/casa-volta",
  },
  {
    id: 3,
    title: "Lattice Pavilion",
    subtitle: "Public cultural centre",
    category: "Cultural",
    location: "Bangalore, IN",
    coords: "12.9716° N, 77.5946° E",
    year: "2023",
    area: "1,900 m²",
    status: "Completed",
    index: "03",
    size: "wide",
    imageSrc: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80&auto=format",
    imageAlt: "Lattice Pavilion",
    href: "/projects/lattice-pavilion",
  },
  {
    id: 4,
    title: "The Void House",
    subtitle: "Minimalist courtyard villa",
    category: "Residential",
    location: "Pondicherry, IN",
    coords: "11.9416° N, 79.8083° E",
    year: "2022",
    area: "420 m²",
    status: "Completed",
    index: "04",
    size: "square",
    imageSrc: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format",
    imageAlt: "The Void House",
    href: "/projects/void-house",
  },
  {
    id: 5,
    title: "Forum One",
    subtitle: "Corporate headquarters campus",
    category: "Commercial",
    location: "Hyderabad, IN",
    coords: "17.3850° N, 78.4867° E",
    year: "2022",
    area: "8,400 m²",
    status: "Under Construction",
    index: "05",
    size: "tall",
    imageSrc: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80&auto=format",
    imageAlt: "Forum One HQ",
    href: "/projects/forum-one",
  },
  {
    id: 6,
    title: "Studio Nave",
    subtitle: "Artist live-work loft interiors",
    category: "Interiors",
    location: "Mumbai, IN",
    coords: "19.0760° N, 72.8777° E",
    year: "2021",
    area: "290 m²",
    status: "Completed",
    index: "06",
    size: "square",
    imageSrc: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80&auto=format",
    imageAlt: "Studio Nave Interiors",
    href: "/projects/studio-nave",
  },
];

export const CATEGORIES: ProjectCategory[] = [
  "All",
  "Residential",
  "Commercial",
  "Cultural",
  "Interiors",
];
